config/routes.rb
Rails.application.routes.draw do
  # resources :toys_users, only: %i(new create update)

  # get 'rent/toy/:toy_id', to: 'toys_users#new', as: 'new_rental'
  # post 'rent', to: 'toys_users#create', as: 'toys_users'
  # patch '/rent/toy/:toy_id', to: 'toys_users#update', as: 'toys_user'


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # route route
  root to: 'toys#index'

  resources :users, only: :show

  resources :toymakers do
    resources :toys, only: %i(new index)
  end

  # resources :users, only: [:index, :show]

  # VERB -- PATH (URL) -- CONTROLLER#ACTION
  # get '/toys', to: 'toys#index', as: 'toys'
  # get '/toys/new'
  # post '/toys', to: 'toys#create'
  # get '/toys/:id', to: 'toys#show', as: 'toy'
  # get '/toys/:id/edit', to: 'toys#edit', as: 'toy_edit'
  # patch '/toys/:id', to: 'toys#update'
  # delete '/toys/:id', to: 'toys#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :toys 
    # resources :toys_users, only: %i(new create update)
    
  # route to test serialer return
  get 'rental/:id', to: 'toys_users#show'
  get '/rental/new', to: 'toys_users#new'
  post '/rental', to: 'toys_users#create'
  patch '/rental/:id', to: 'toys_users#update', as: 'rental_update'
end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :toymaker
  has_many :toys_user
  has_many :user, through: :toys_user

  validates :name, :size, :theme, presence: true

  def currently_rented?(user)
    # ToysUser.toy_currently_rented?(self, user)
    toys_user.where(toy_return_date: [nil, ''], user_id: user.id) != []
  end

  # find rental contract
  def contract(user)
    toys_user.find_by(user_id: user.id)
  end

  def past_rental_date(user)
    # ToysUser.past_toy_rentals(self, user)
    result = toys_user.where(user_id: user.id).where.not(toy_return_date: [nil, ''])
    return result[0].toy_return_date if result != []
  end

  # def self.find_past_rentals(arr)
  #   # arr.map {|obj| self.find(obj.toy_id)}
  #   # arr.map {|obj| obj.toy}
  #   arr.map(&:toy)
  # end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :set_toy, only: [:show, :edit, :update, :destroy]

  def index
   # byebug
   @toymakers = Toymaker.all
   if params[:toymaker_id]
     @toys = Toymaker.find(params[:toymaker_id]).toys
   else
    @toys = Toy.all
   end
  end

  def new
    # binding.pry
    @toy = Toy.new(toymaker_id: params[:toymaker_id])
    @toymakers = Toymaker.all 
  end

  def create
    # binding.pry
    # byebug
    @toy = Toy.new(toy_params)
    if @toy.save
      redirect_to toy_path(@toy)
    else
      @toymakers = Toymaker.all 
      render :new
    end
  end

  def show
  end

  def edit
    # binding.pry
    @toymakers = Toymaker.all 

  end

  def update
    # byebug
    if @toy.update(toy_params)
      redirect_to toy_path(@toy)
    else
      @toymakers = Toymaker.all 
      render :edit
    end
  end

  def destroy
    # byebug
    @toy.destroy
    redirect_to toys_path
  end

  private
  #strong params
  def toy_params
    params.require(:toy).permit(:name, :size, :theme, :toymaker_id)
  end

  def set_toy
    @toy = Toy.find(params[:id])
  end

end

app/helpers/toys_helper.rb
module ToysHelper
  def toymaker_link(toy)
    if toy.toymaker
      link_to toy.toymaker.brand, toymaker_path(toy.toymaker)
    else
      link_to 'Add a Toymaker', toy_edit_path(toy)
    end
  end

  def title_message(toys)
    # byebug
    if toys.length < 5
      'This toybox has so few toys!'
    else
      'This toybox has a lot of toys!'
    end
  end
end

app/views/toys/_form.html.erb
<%= form_for form_toy do |f|  %>
  <%= f.label (:name) %>
  <%= f.text_field(:name) %>
  <br/>
  <%= f.label :size %>
  <%= f.text_field(:size) %>
  <br/>
  <%= f.label( :theme) %>
  <%= f.text_field(:theme) %>
  <br/>
  <!-- <label>Owner</label><br/> -->
  <%#= collection_radio_buttons(:toy, :user_id, @users, :id, :username)%>
  <%# @users.each do |user| %>
   <%#= radio_button_tag(:user_id, user.id)%><%#=  user.username %>
  <%# end %>

  <br>
  <label>Toymaker</label><br/>
  <%= collection_radio_buttons(:toy, :toymaker_id, @toymakers, :id, :brand)%>

  <%# @toymakers.each do |toymaker| %>
   <%#= radio_button_tag(:toymaker_id, toymaker.id)%><%#= toymaker.brand %>
  <%# end %>
  
  <%# collection_radio_buttons(:post, :author_id, Author.all, :id, :name_with_initial) %>


  <br/>
  <%= f.submit%>
<% end %>

app/views/toys/edit.html.erb
<h1>Edit a Toy</h1>
<%= error_messages(@toy) %>

 <%= render 'form', form_toy: @toy %>

app/views/toys/index.html.erb
<h1><%= title_message(@toys) %></h1>

<% if current_user %>
  <h2>Lets add more! =D</h2>
  <h4>Add by Brand or just <%= link_to 'Add a toy', new_toy_path %></h4>
    <ul><% @toymakers.each do |toymaker| %>
      <li><%= link_to toymaker.brand, new_toymaker_toy_path(toymaker) %></li>
    <% end %></ul>
<% else %>
  <p><%= link_to 'Login', user_session_path %>  or <%= link_to 'SignUp', new_user_registration_path %> to add toys to our toybox</p>
<% end %>

<br/>
<div id='confirmMessage'>
</div>
<br/>

<h2>Here's all the Toys in our ToyBox</h2>

<ul>
  <% @toys.each do |toy| %>
    <li>
      <b><%= link_to toy.name, toy_path(toy) %></b> make by <b><%= toy.toymaker.brand  %></b>
      <%= link_to 'Rent Me', '#', {id: 'rentToy', data: {toy_id: toy.id}} if user_signed_in? %>
      <div id='formRentToy-<%= toy.id%>'>
      </div>
    </li>
  <% end %>
</ul>

<div id='hidden' style='display:none'>
  <%= render 'toys_users/form', {toyuser: ToysUser.new(toy_rent_date: Date.today)}%>
</div>

app/views/toys/new.html.erb
<h1>Add a NEW Toy</h1>
<%= error_messages(@toy) %>

 <%= render 'form', form_toy: @toy %>
 <%#= render partial: 'form', locals: {form_toy: @toy} %>

app/views/toys/show.html.erb
<h1><%= @toy.name %></h1>
<h3>This toy was made by <em><%= @toy.toymaker.brand%></h3></em>

<p>Size: <%= @toy.size %></p>
<p>Theme: <%= @toy.theme %></p>
<%= button_to 'Rent Me', toy_rental_new_path(@toy), method: :get %>

<%= button_to 'Remove Toy', toy_path(@toy), method: :delete, data: {confirm: 'Is the toy really broken!'}%>