config/routes.rb
Rails.application.routes.draw do
  # resources :toys_users, only: %i(new create update)

  # get 'rent/toy/:toy_id', to: 'toys_users#new', as: 'new_rental'
  # post 'rent', to: 'toys_users#create', as: 'toys_users'
  # patch '/rent/toy/:toy_id', to: 'toys_users#update', as: 'toys_user'


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # route route
  root to: 'toys#index'

  resources :users, only: :show

  resources :toymakers do
    resources :toys, only: %i(new index)
  end

  # resources :users, only: [:index, :show]

  # VERB -- PATH (URL) -- CONTROLLER#ACTION
  # get '/toys', to: 'toys#index', as: 'toys'
  # get '/toys/new'
  # post '/toys', to: 'toys#create'
  # get '/toys/:id', to: 'toys#show', as: 'toy'
  # get '/toys/:id/edit', to: 'toys#edit', as: 'toy_edit'
  # patch '/toys/:id', to: 'toys#update'
  # delete '/toys/:id', to: 'toys#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :toys 
    # resources :toys_users, only: %i(new create update)
    
  # route to test serialer return
  get 'rental/:id', to: 'toys_users#show'
  get '/rental/new', to: 'toys_users#new'
  post '/rental', to: 'toys_users#create'
  patch '/rental/:id', to: 'toys_users#update', as: 'rental_update'
end

app/models/toymaker.rb
class Toymaker < ApplicationRecord
  has_many :toys
  has_many :users, through: :toys

  accepts_nested_attributes_for :toys

  validates :brand, :age, :kind, presence: true

  def opening_year
    "This company started in #{Time.now.year - self.age} year, and is #{self.age}  years old!"
  end
end

app/controllers/toymakers_controller.rb
class ToymakersController < ApplicationController
  before_action :authenticate_user!, except: %i(index show)
  before_action :set_toymaker, only: [:show, :edit, :update, :destroy]

  def index
    @toymakers = Toymaker.all
  end

  def new
    @toymaker = Toymaker.new()
    @toymaker.toys.build
  end

  def create
    # binding.pry
    # byebug
    @toymaker = Toymaker.new(toymaker_params)
    if @toymaker.save
      redirect_to toymaker_path(toymaker)
    else
      # byebug
      render :new
    end
  end

  def show
    # byebug
    # VIEW_HELPER_METHOD
    # opening_year(@toymaker) #=> error undef method (PR method)
    # MODEL_METHOD
    # @toymaker.opening_year #=> this is an instance method (OOR method)
  end

  def edit

  end

  def update
    # byebug
    @toymaker.update(toymaker_params)
    redirect_to toymaker_path(@toymaker)
  end

  def destroy
    # byebug
    @toymaker.destroy
    redirect_to toymakers_path
  end

  private
  #strong params
  def toymaker_params
    params.require(:toymaker).permit(:brand, :kind, :age, toys_attributes: [
      :name,
      :size,
      :theme
    ])
  end

  #how drawing of how the params will look
  # params {
  #   auth_token: ....,
  #   toymaker: {
  #     brand: ..,
  #     kind: ...,
  #     age: ...,
  # toy_attributes is set equal to an array to allow multiple toy_obj values to be created
  # the keys associate w/in toys_attributes hash rep index (or location) of element in arr
  #     toys_attributes: {
  #       0: {name:...., size: ..., theme: ...},
  #       1: {name:...., size: ..., theme: ...}
  #     }
  #   }
  # }

  def set_toymaker
    @toymaker = Toymaker.find(params[:id])
  end

end

app/helpers/toymakers_helper.rb
module ToymakersHelper
  def opening_year(toymaker)
    "This company started in #{Time.now.year - toymaker.age} year, and is #{toymaker.age}  years old!"
  end
end

app/views/toymakers/index.html.erb
<h1>The toy industry is <em>BOOM'N!</em></h1>
<% if @toymakers == {} #current_user temporary conditional, to stop code from breaking, need to build #current_user %>
  <h2>Are we missing your <em>favorite</em> toymaker?</h2>
  <h4>Add them here: <%= link_to 'New toymaker', new_toymaker_path %></h4>
<% else %>
  <p>Login or SignUp to add toys to our toybox</p>
<% end %>

<ul><% @toymakers.each do |toymaker| %>
  <li><b><%= link_to toymaker.brand, toymaker_path(toymaker) %></b> this buisness has been around for <b><%= toymaker.age %></b> years! </li>
<% end %></ul>

app/views/toymakers/new.html.erb
<h1>WELCOME Toymaker!</h1>
<h3>Add some info about your Co.!</h3>

<%= error_messages(@toymaker) %>

<%= form_for @toymaker do |f|  %>
  <%= f.label (:brand) %>
  <%= f.text_field(:brand) %>
  <br/>
  <%= f.label :kind %>
  <%= f.text_field(:kind) %>
  <br/>
  <%= f.label( :age) %>
  <%= f.text_field(:age) %>
  <br/>
  <h3>Add some of your toys, plz =D </h3>
  <%= f.fields_for :toys do |t| %>
    <%= t.label (:name) %>
    <%= t.text_field(:name) %>
    <br/>
    <%= t.label :size %>
    <%= t.text_field(:size) %>
    <br/>
    <%= t.label( :theme) %>
    <%= t.text_field(:theme) %>
  <br/>
  <br/>
  <% end %>
  <br/>
  <%= f.submit%>
<% end %>

app/views/toymakers/show.html.erb
<h1><%= @toymaker.brand %> Toys</h1>
<p> <%= opening_year(@toymaker) %></p>
<% @toymaker.toys.each do |toy| %>
<h3>Name: <%= toy.name %></h3>
<p>Size: <%= toy.size %></p>
<p>Theme: <%= toy.theme %></p>
<br />
<br />
<% end %>
<%#= button_to 'Remove Toy', toy_path(@toy), method: :delete, data: {confirm: 'Is the toy really broken!'}%>