config/routes.rb
Rails.application.routes.draw do
  # resources :toys_users, only: %i(new create update)

  # get 'rent/toy/:toy_id', to: 'toys_users#new', as: 'new_rental'
  # post 'rent', to: 'toys_users#create', as: 'toys_users'
  # patch '/rent/toy/:toy_id', to: 'toys_users#update', as: 'toys_user'


  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # route route
  root to: 'toys#index'

  resources :users, only: :show

  resources :toymakers do
    resources :toys, only: %i(new index)
  end

  # resources :users, only: [:index, :show]

  # VERB -- PATH (URL) -- CONTROLLER#ACTION
  # get '/toys', to: 'toys#index', as: 'toys'
  # get '/toys/new'
  # post '/toys', to: 'toys#create'
  # get '/toys/:id', to: 'toys#show', as: 'toy'
  # get '/toys/:id/edit', to: 'toys#edit', as: 'toy_edit'
  # patch '/toys/:id', to: 'toys#update'
  # delete '/toys/:id', to: 'toys#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :toys 
    # resources :toys_users, only: %i(new create update)
    
  # route to test serialer return
  get 'rental/:id', to: 'toys_users#show'
  get '/rental/new', to: 'toys_users#new'
  post '/rental', to: 'toys_users#create'
  patch '/rental/:id', to: 'toys_users#update', as: 'rental_update'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_many :toys_user
  has_many :toys, through: :toys_user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2, :amazon]

  def self.from_omniauth(auth)
    # Either create a User record or update it based on the provider (Google) and the UID
    # binding.pry
    self.where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.name
      user.email = auth.info.email
      # user.password = Devise.friendly_token[0,20]
      # binding.pry
      user.password = user.email.reverse
    end
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: :show

  def show
    # need to protect routes
      # binding.pry
      # binding.pry
    @rentals = ToysUser.user_past_rentals(@user)
    @toys = @rentals.map(&:toy)
    redirect_to new_user_session_path if current_user.id != @user.id
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h1>Hi <%= @user.username %>!</h1> <%= link_to 'Edit Profile',  edit_user_registration_path %>
  <h3>Here are the toys your <em>current & future</em> rental</h3>
  <p>Future rentals are enclosed in a <b style="
    color: orange">ORANGE</b> box</p>
  <ul>
  <% @user.toys.each do |toy| %>
    <% if toy.currently_rented?(@user) %>
    <% contract = toy.contract(@user) %>
      <li class =<%= "future-rental" unless (contract.toy_rent_date <= Date.today) %> >
        Checkout date: <b><%= contract.toy_rent_date.strftime("%a. %B %d, %Y") %></b></br>
        <%= link_to toy.name, toy_path(toy) %>
        <p>Created by: <%= toymaker_link(toy)  %></p>
        <%# binding.pry %>
        <%#= button_to 'Return Toy', toy_rental_update_path(toy,  toy.contract(@user)),
        method: :patch %>
      </li>
    <% end %>
  <% end %>
</ul>

<h3>Here are the toys your <em>past</em> rentals!</h3>
<p><em>Using model methods</em></p>
<ol>
<% @user.toys.each do |toy| %>
    <% date = toy.past_rental_date(@user)%>
    <% if date %>
      <li>
        <p><%= link_to toy.name, toy_path(toy) %> Created by: <%= toymaker_link(toy)  %>
        </p>
        <p>Returned on <b><%= date.strftime("%a. %B %d, %Y") %></b></p>
      </li>
    <% end %>
  <% end %>
</ol>